window.YINSCENT_PRODUCTS = [
  { id: "orange-blossom", name: "Orange Blossom", slug: "orange-blossom", desc: "Refreshing orange blossom aroma", price: "6.90", featured: false },
  { id: "strawberry-cream", name: "Strawberry Cream", slug: "strawberry-cream", desc: "Sweet strawberry cream aroma", price: "6.90", featured: false },

  /* 9-pack scented tea light candles (new line) */
  { id: "lavender-pack", name: "Lavender — 9 Pack", slug: "lavender-pack", desc: "Calming lavender · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Lavender (9 Pack)" },
  { id: "cotton-pack", name: "Cotton — 9 Pack", slug: "cotton-pack", desc: "Clean cotton · 9 tea lights · smokeless clean burn", price: "9.90", featured: false, cartName: "Scented Tea Light Candles — Cotton (9 Pack)" },
  { id: "cherry-pack", name: "Cherry — 9 Pack", slug: "cherry-pack", desc: "Sweet cherry · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Cherry (9 Pack)" },
  { id: "apple-pack", name: "Apple — 9 Pack", slug: "apple-pack", desc: "Crisp apple · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Apple (9 Pack)" },
  { id: "rose-pack", name: "Rose — 9 Pack", slug: "rose-pack", desc: "Romantic rose · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Rose (9 Pack)" },
  { id: "jasmine-pack", name: "Jasmine — 9 Pack", slug: "jasmine-pack", desc: "Delicate jasmine · 9 tea lights · smokeless clean burn", price: "9.90", featured: false, cartName: "Scented Tea Light Candles — Jasmine (9 Pack)" },
  { id: "coconut-pack", name: "Coconut — 9 Pack", slug: "coconut-pack", desc: "Creamy coconut · 9 tea lights · smokeless clean burn", price: "9.90", featured: false, cartName: "Scented Tea Light Candles — Coconut (9 Pack)" },
  { id: "cinnamon-pack", name: "Cinnamon — 9 Pack", slug: "cinnamon-pack", desc: "Warm cinnamon · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Cinnamon (9 Pack)" },
  { id: "mango-pack", name: "Mango — 9 Pack", slug: "mango-pack", desc: "Sweet mango · 9 tea lights · smokeless clean burn", price: "9.90", featured: false, cartName: "Scented Tea Light Candles — Mango (9 Pack)" },
  { id: "vanilla-pack", name: "Vanilla — 9 Pack", slug: "vanilla-pack", desc: "Rich vanilla · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Vanilla (9 Pack)" },
  { id: "ocean-pack", name: "Ocean — 9 Pack", slug: "ocean-pack", desc: "Fresh ocean breeze · 9 tea lights · smokeless clean burn", price: "9.90", featured: true, cartName: "Scented Tea Light Candles — Ocean (9 Pack)" },

  /* Cozy collection — scented tealight candles (additional line, new images) */
  { id: "vanilla-cozy", name: "Vanilla — Cozy", slug: "vanilla-cozy", desc: "Creamy vanilla aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Vanilla (Cozy)" },
  { id: "cotton-cozy", name: "Cotton — Cozy", slug: "cotton-cozy", desc: "Soft cotton aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Cotton (Cozy)" },
  { id: "cherry-cozy", name: "Cherry — Cozy", slug: "cherry-cozy", desc: "Sweet cherry aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Cherry (Cozy)" },
  { id: "cinnamon-cozy", name: "Cinnamon — Cozy", slug: "cinnamon-cozy", desc: "Warm cinnamon aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Cinnamon (Cozy)" },
  { id: "rose-cozy", name: "Rose — Cozy", slug: "rose-cozy", desc: "Romantic rose aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Rose (Cozy)" },
  { id: "mango-cozy", name: "Mango — Cozy", slug: "mango-cozy", desc: "Juicy mango aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Mango (Cozy)" },
  { id: "lavender-cozy", name: "Lavender — Cozy", slug: "lavender-cozy", desc: "Relaxing lavender aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Lavender (Cozy)" },
  { id: "ocean-cozy", name: "Ocean — Cozy", slug: "ocean-cozy", desc: "Fresh ocean aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Ocean (Cozy)" },
  { id: "jasmine-cozy", name: "Jasmine — Cozy", slug: "jasmine-cozy", desc: "Delicate jasmine aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Jasmine (Cozy)" },
  { id: "apple-cozy", name: "Apple — Cozy", slug: "apple-cozy", desc: "Juicy apple aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Apple (Cozy)" },
  { id: "coconut-cozy", name: "Coconut — Cozy", slug: "coconut-cozy", desc: "Fresh coconut aroma · long lasting burn · premium wax", price: "6.90", featured: false, cartName: "Scented Tealight Candles — Coconut (Cozy)" },

  /* Scented candles — jar collection */
  {
    id: "cotton-candle",
    name: "Cotton",
    slug: "cotton-candle",
    category: "scented-candles",
    desc: "Fresh cotton · clean & soft · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Cotton (260g)",
    tagline: "Fresh. Soft. Comforting.",
    images: ["cotton-candle", "cotton-candle-lit", "cotton-candle-display"],
    features: [
      { icon: "☁", label: "Fresh cotton", text: "Clean & soft" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "orange-blossom-candle",
    name: "Orange Blossom",
    slug: "orange-blossom-candle",
    category: "scented-candles",
    desc: "Bright orange blossom · floral & refreshing · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Orange Blossom (260g)",
    tagline: "Bright. Floral. Refreshing.",
    images: ["orange-blossom-candle", "orange-blossom-candle-lit", "orange-blossom-candle-display"],
    features: [
      { icon: "✿", label: "Orange blossom", text: "Floral & refreshing" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "apple-candle",
    name: "Apple",
    slug: "apple-candle",
    category: "scented-candles",
    desc: "Crisp apple · fresh & delightful · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Apple (260g)",
    tagline: "Crisp. Fresh. Delightful.",
    images: ["apple-candle", "apple-candle-lit", "apple-candle-display"],
    features: [
      { icon: "◆", label: "Crisp apple", text: "Fresh & delightful" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "lavender-candle",
    name: "Lavender",
    slug: "lavender-candle",
    category: "scented-candles",
    desc: "Soothing lavender · calm & relax · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Lavender (260g)",
    tagline: "Relax. Unwind. Breathe.",
    images: ["lavender-candle", "lavender-candle-lit", "lavender-candle-display"],
    features: [
      { icon: "❀", label: "Soothing lavender", text: "Calm & relax" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "rose-candle",
    name: "Rose",
    slug: "rose-candle",
    category: "scented-candles",
    desc: "Romantic rose · soft & floral · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Rose (260g)",
    tagline: "Romantic. Elegant. Timeless.",
    images: ["rose-candle-lit", "rose-candle", "rose-candle-display"],
    features: [
      { icon: "✿", label: "Romantic rose", text: "Soft & floral" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "ocean-candle",
    name: "Ocean",
    slug: "ocean-candle",
    category: "scented-candles",
    desc: "Fresh ocean · clean & refreshing · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Ocean (260g)",
    tagline: "Fresh. Clean. Refreshing.",
    images: ["ocean-candle", "ocean-candle-lit", "ocean-candle-display"],
    features: [
      { icon: "≋", label: "Fresh ocean", text: "Clean & refreshing" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "mango-candle",
    name: "Mango",
    slug: "mango-candle",
    category: "scented-candles",
    desc: "Juicy mango · sweet & tropical · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Mango (260g)",
    tagline: "Tropical. Sweet. Uplifting.",
    images: ["mango-candle-lit", "mango-candle", "mango-candle-display"],
    features: [
      { icon: "◆", label: "Juicy mango", text: "Sweet & tropical" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "jasmine-candle",
    name: "Jasmine",
    slug: "jasmine-candle",
    category: "scented-candles",
    desc: "Jasmine blossom · elegant & floral · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Jasmine (260g)",
    tagline: "Elegant. Floral. Soothing.",
    images: ["jasmine-candle", "jasmine-candle-lit", "jasmine-candle-display"],
    features: [
      { icon: "❀", label: "Jasmine blossom", text: "Elegant & floral" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "cinnamon-candle",
    name: "Cinnamon",
    slug: "cinnamon-candle",
    category: "scented-candles",
    desc: "Warm cinnamon · spicy & comforting · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Cinnamon (260g)",
    tagline: "Warm. Spicy. Comforting.",
    images: ["cinnamon-candle", "cinnamon-candle-lit", "cinnamon-candle-display"],
    features: [
      { icon: "✦", label: "Warm cinnamon", text: "Spicy & comforting" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "coconut-candle",
    name: "Coconut",
    slug: "coconut-candle",
    category: "scented-candles",
    desc: "Creamy coconut · soft & tropical · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Coconut (260g)",
    tagline: "Creamy. Tropical. Calming.",
    images: ["coconut-candle", "coconut-candle-lit", "coconut-candle-display"],
    features: [
      { icon: "◆", label: "Creamy coconut", text: "Soft & tropical" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "cherry-candle",
    name: "Cherry",
    slug: "cherry-candle",
    category: "scented-candles",
    desc: "Juicy cherry · sweet & fruity · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Cherry (260g)",
    tagline: "Rich. Juicy. Indulgent.",
    images: ["cherry-candle", "cherry-candle-lit", "cherry-candle-display"],
    features: [
      { icon: "◆", label: "Juicy cherries", text: "Sweet & fruity" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "strawberry-cream-candle",
    name: "Strawberry Cream",
    slug: "strawberry-cream-candle",
    category: "scented-candles",
    desc: "Fresh strawberries · sweet & creamy · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Strawberry Cream (260g)",
    tagline: "Sweet. Creamy. Delightful.",
    images: ["strawberry-cream-candle", "strawberry-cream-candle-lit", "strawberry-cream-candle-display"],
    features: [
      { icon: "◆", label: "Fresh strawberries", text: "Sweet & creamy" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "vanilla-candle",
    name: "Vanilla",
    slug: "vanilla-candle",
    category: "scented-candles",
    desc: "Classic vanilla · sweet & smooth · up to 45 hours · 260g",
    price: "14.90",
    featured: true,
    cartName: "Scented Candle — Vanilla (260g)",
    tagline: "Soft. Warm. Comforting.",
    images: ["vanilla-candle", "vanilla-candle-lit", "vanilla-candle-display"],
    features: [
      { icon: "❀", label: "Classic vanilla", text: "Sweet & smooth" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },

  /* Reed diffusers — 35 ml */
  {
    id: "apple-diffuser-35",
    name: "Apple — 35 ml",
    slug: "apple-diffuser-35",
    category: "reed-diffusers",
    desc: "Sweet & juicy apple · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Apple (35 ml)",
    tagline: "Sweet. Juicy. Comforting.",
    features: [
      { icon: "◆", label: "Sweet apple", text: "Juicy & comforting" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "mango-diffuser-35",
    name: "Mango — 35 ml",
    slug: "mango-diffuser-35",
    category: "reed-diffusers",
    desc: "Vivid & juicy mango · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Mango (35 ml)",
    tagline: "Sweet. Tropical. Refreshing.",
    features: [
      { icon: "◆", label: "Juicy mango", text: "Vivid & tropical" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "cinnamon-diffuser-35",
    name: "Cinnamon — 35 ml",
    slug: "cinnamon-diffuser-35",
    category: "reed-diffusers",
    desc: "Warm & spicy cinnamon · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Cinnamon (35 ml)",
    tagline: "Warm. Spicy. Comforting.",
    features: [
      { icon: "✦", label: "Warm cinnamon", text: "Spicy & cozy" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "cotton-diffuser-35",
    name: "Cotton — 35 ml",
    slug: "cotton-diffuser-35",
    category: "reed-diffusers",
    desc: "Pure & clean cotton · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Cotton (35 ml)",
    tagline: "Fresh. Clean. Comforting.",
    features: [
      { icon: "☁", label: "Pure cotton", text: "Clean & soft" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "cherry-diffuser-35",
    name: "Cherry — 35 ml",
    slug: "cherry-diffuser-35",
    category: "reed-diffusers",
    desc: "Sweet & delicate cherry · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Cherry (35 ml)",
    tagline: "Sweet. Fruity. Delicate.",
    features: [
      { icon: "◆", label: "Sweet cherry", text: "Fruity & delicate" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "ocean-diffuser-35",
    name: "Ocean — 35 ml",
    slug: "ocean-diffuser-35",
    category: "reed-diffusers",
    desc: "Fresh & marine ocean · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Ocean (35 ml)",
    tagline: "Fresh. Clean. Refreshing.",
    features: [
      { icon: "≋", label: "Fresh ocean", text: "Marine & clean" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "jasmine-diffuser-35",
    name: "Jasmine — 35 ml",
    slug: "jasmine-diffuser-35",
    category: "reed-diffusers",
    desc: "Elegant & floral jasmine · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Jasmine (35 ml)",
    tagline: "Pure. Floral. Serene.",
    features: [
      { icon: "❀", label: "Jasmine blossom", text: "Elegant & floral" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "lavender-diffuser-35",
    name: "Lavender — 35 ml",
    slug: "lavender-diffuser-35",
    category: "reed-diffusers",
    desc: "Relaxing lavender · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Lavender (35 ml)",
    tagline: "Breathe in lavender. Feel the calm.",
    features: [
      { icon: "❀", label: "Soothing lavender", text: "Calm & relax" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "orange-blossom-diffuser-35",
    name: "Orange Blossom — 35 ml",
    slug: "orange-blossom-diffuser-35",
    category: "reed-diffusers",
    desc: "Fresh & floral orange blossom · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Orange Blossom (35 ml)",
    tagline: "Fresh. Floral. Uplifting.",
    features: [
      { icon: "✿", label: "Orange blossom", text: "Floral & refreshing" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "coconut-diffuser-35",
    name: "Coconut — 35 ml",
    slug: "coconut-diffuser-35",
    category: "reed-diffusers",
    desc: "Tropical & creamy coconut · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Coconut (35 ml)",
    tagline: "Tropical. Creamy. Comforting.",
    features: [
      { icon: "◆", label: "Creamy coconut", text: "Tropical & soothing" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "vanilla-diffuser-35",
    name: "Vanilla — 35 ml",
    slug: "vanilla-diffuser-35",
    category: "reed-diffusers",
    desc: "Creamy vanilla · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Vanilla (35 ml)",
    tagline: "Warm. Creamy. Comforting.",
    features: [
      { icon: "◆", label: "Creamy vanilla", text: "Warm & comforting" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },
  {
    id: "rose-diffuser-35",
    name: "Rose — 35 ml",
    slug: "rose-diffuser-35",
    category: "reed-diffusers",
    desc: "Romantic rose · natural rattan sticks · up to 8+ weeks · 35 ml",
    price: "11.90",
    featured: true,
    cartName: "Reed Diffuser — Rose (35 ml)",
    tagline: "Romantic. Soft. Timeless.",
    features: [
      { icon: "✿", label: "Romantic rose", text: "Soft & floral" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "35 ml", text: "Compact size" },
    ],
  },

  /* Reed diffusers — 100 ml */
  {
    id: "apple-diffuser",
    name: "Apple — 100 ml",
    slug: "apple-diffuser",
    category: "reed-diffusers",
    desc: "Sweet & juicy apple · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Apple (100 ml)",
    tagline: "Sweet. Juicy. Comforting.",
    features: [
      { icon: "◆", label: "Sweet apple", text: "Juicy & comforting" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "mango-diffuser",
    name: "Mango — 100 ml",
    slug: "mango-diffuser",
    category: "reed-diffusers",
    desc: "Vivid & juicy mango · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Mango (100 ml)",
    tagline: "Sweet. Tropical. Refreshing.",
    features: [
      { icon: "◆", label: "Juicy mango", text: "Vivid & tropical" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "cinnamon-diffuser",
    name: "Cinnamon — 100 ml",
    slug: "cinnamon-diffuser",
    category: "reed-diffusers",
    desc: "Warm & spicy cinnamon · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Cinnamon (100 ml)",
    tagline: "Warm. Spicy. Comforting.",
    features: [
      { icon: "✦", label: "Warm cinnamon", text: "Spicy & cozy" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "cotton-diffuser",
    name: "Cotton — 100 ml",
    slug: "cotton-diffuser",
    category: "reed-diffusers",
    desc: "Pure & clean cotton · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Cotton (100 ml)",
    tagline: "Fresh. Clean. Comforting.",
    features: [
      { icon: "☁", label: "Pure cotton", text: "Clean & soft" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "cherry-diffuser",
    name: "Cherry — 100 ml",
    slug: "cherry-diffuser",
    category: "reed-diffusers",
    desc: "Sweet & delicate cherry · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Cherry (100 ml)",
    tagline: "Sweet. Fruity. Delicate.",
    features: [
      { icon: "◆", label: "Sweet cherry", text: "Fruity & delicate" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "ocean-diffuser",
    name: "Ocean — 100 ml",
    slug: "ocean-diffuser",
    category: "reed-diffusers",
    desc: "Fresh & marine ocean · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Ocean (100 ml)",
    tagline: "Fresh. Clean. Refreshing.",
    features: [
      { icon: "≋", label: "Fresh ocean", text: "Marine & clean" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "jasmine-diffuser",
    name: "Jasmine — 100 ml",
    slug: "jasmine-diffuser",
    category: "reed-diffusers",
    desc: "Elegant & floral jasmine · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Jasmine (100 ml)",
    tagline: "Pure. Floral. Serene.",
    features: [
      { icon: "❀", label: "Jasmine blossom", text: "Elegant & floral" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "lavender-diffuser",
    name: "Lavender — 100 ml",
    slug: "lavender-diffuser",
    category: "reed-diffusers",
    desc: "Relaxing lavender · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Lavender (100 ml)",
    tagline: "Breathe in lavender. Feel the calm.",
    features: [
      { icon: "❀", label: "Soothing lavender", text: "Calm & relax" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "orange-blossom-diffuser",
    name: "Orange Blossom — 100 ml",
    slug: "orange-blossom-diffuser",
    category: "reed-diffusers",
    desc: "Fresh & floral orange blossom · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Orange Blossom (100 ml)",
    tagline: "Fresh. Floral. Uplifting.",
    features: [
      { icon: "✿", label: "Orange blossom", text: "Floral & refreshing" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "coconut-diffuser",
    name: "Coconut — 100 ml",
    slug: "coconut-diffuser",
    category: "reed-diffusers",
    desc: "Tropical & creamy coconut · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Coconut (100 ml)",
    tagline: "Tropical. Creamy. Comforting.",
    features: [
      { icon: "◆", label: "Creamy coconut", text: "Tropical & soothing" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "vanilla-diffuser",
    name: "Vanilla — 100 ml",
    slug: "vanilla-diffuser",
    category: "reed-diffusers",
    desc: "Creamy vanilla · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Vanilla (100 ml)",
    tagline: "Warm. Creamy. Comforting.",
    features: [
      { icon: "◆", label: "Creamy vanilla", text: "Warm & comforting" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },
  {
    id: "rose-diffuser",
    name: "Rose — 100 ml",
    slug: "rose-diffuser",
    category: "reed-diffusers",
    desc: "Romantic rose · natural rattan sticks · up to 8+ weeks · 100 ml",
    price: "16.90",
    featured: true,
    cartName: "Reed Diffuser — Rose (100 ml)",
    tagline: "Romantic. Soft. Timeless.",
    features: [
      { icon: "✿", label: "Romantic rose", text: "Soft & floral" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "100 ml", text: "Full size" },
    ],
  },

  /* Tealight holders */
  {
    id: "square-tealight-holder",
    name: "Square — 12 Pack",
    slug: "square-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · square shape · 7.5 × 4.3 cm · 12 pcs value pack",
    price: "12.90",
    featured: true,
    cartName: "Tealight Holder — Square (12 Pack)",
    tagline: "Elegant. Transparent. Timeless.",
    features: [
      { icon: "▢", label: "Square shape", text: "Modern & clean" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
  {
    id: "star-tealight-holder",
    name: "Star — 12 Pack",
    slug: "star-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · star shape · 9.8 × 4.3 cm · 12 pcs value pack",
    price: "12.90",
    featured: true,
    cartName: "Tealight Holder — Star (12 Pack)",
    tagline: "Sparkling. Charming. Festive.",
    features: [
      { icon: "★", label: "Star shape", text: "Eye-catching glow" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
  {
    id: "heart-tealight-holder",
    name: "Heart — 12 Pack",
    slug: "heart-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · heart shape · 8.5 × 4.2 cm · 12 pcs value pack",
    price: "12.90",
    featured: true,
    cartName: "Tealight Holder — Heart (12 Pack)",
    tagline: "Romantic. Warm. Delightful.",
    features: [
      { icon: "♥", label: "Heart shape", text: "Romantic & warm" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
  {
    id: "plum-blossom-tealight-holder",
    name: "Plum Blossom — 12 Pack",
    slug: "plum-blossom-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · plum blossom shape · 9.5 × 4.3 cm · 12 pcs value pack",
    price: "12.90",
    featured: true,
    cartName: "Tealight Holder — Plum Blossom (12 Pack)",
    tagline: "Floral. Graceful. Radiant.",
    features: [
      { icon: "✿", label: "Plum blossom", text: "Floral & graceful" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },

  /* Scented sachets */
  {
    id: "apple-sachet",
    name: "Apple",
    slug: "apple-sachet",
    category: "scented-sachets",
    desc: "Warm apple aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Apple (12 Pack)",
    tagline: "Warm aroma. Natural elegance.",
    ref: "Y987S031",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Warm apple scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "coconut-sachet",
    name: "Coconut",
    slug: "coconut-sachet",
    category: "scented-sachets",
    desc: "Tropical coconut aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Coconut (12 Pack)",
    tagline: "Tropical freshness. Natural elegance.",
    ref: "Y987S026",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Creamy coconut scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "orange-blossom-sachet",
    name: "Orange Blossom",
    slug: "orange-blossom-sachet",
    category: "scented-sachets",
    desc: "Floral orange blossom · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Orange Blossom (12 Pack)",
    tagline: "Floral freshness. Natural elegance.",
    ref: "Y987S033",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Orange blossom scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "ocean-sachet",
    name: "Ocean",
    slug: "ocean-sachet",
    category: "scented-sachets",
    desc: "Fresh ocean aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Ocean (12 Pack)",
    tagline: "Marine freshness. Natural elegance.",
    ref: "Y987S024",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Fresh ocean scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "jasmine-sachet",
    name: "Jasmine",
    slug: "jasmine-sachet",
    category: "scented-sachets",
    desc: "Elegant jasmine aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Jasmine (12 Pack)",
    tagline: "Floral freshness. Natural elegance.",
    ref: "Y987S032",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Elegant jasmine scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "cotton-sachet",
    name: "Cotton",
    slug: "cotton-sachet",
    category: "scented-sachets",
    desc: "Clean cotton aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Cotton (12 Pack)",
    tagline: "Natural freshness. Lasting elegance.",
    ref: "Y987S028",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Clean cotton scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "mango-sachet",
    name: "Mango",
    slug: "mango-sachet",
    category: "scented-sachets",
    desc: "Tropical mango aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Mango (12 Pack)",
    tagline: "Tropical freshness. Natural elegance.",
    ref: "Y987S030",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Juicy mango scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "cinnamon-sachet",
    name: "Cinnamon",
    slug: "cinnamon-sachet",
    category: "scented-sachets",
    desc: "Warm cinnamon aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Cinnamon (12 Pack)",
    tagline: "Warm aroma. Natural elegance.",
    ref: "Y987S027",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Warm cinnamon scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "rose-sachet",
    name: "Rose",
    slug: "rose-sachet",
    category: "scented-sachets",
    desc: "Romantic rose aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Rose (12 Pack)",
    tagline: "Warm aroma. Natural elegance.",
    ref: "Y987S029",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Romantic rose scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "vanilla-sachet",
    name: "Vanilla",
    slug: "vanilla-sachet",
    category: "scented-sachets",
    desc: "Creamy vanilla aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Vanilla (12 Pack)",
    tagline: "Warm aroma. Natural elegance.",
    ref: "Y987S025",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Creamy vanilla scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "cherry-sachet",
    name: "Cherry",
    slug: "cherry-sachet",
    category: "scented-sachets",
    desc: "Sweet cherry aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Cherry (12 Pack)",
    tagline: "Fruity freshness. Natural elegance.",
    ref: "Y987S034",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Sweet cherry scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },
  {
    id: "lavender-sachet",
    name: "Lavender",
    slug: "lavender-sachet",
    category: "scented-sachets",
    desc: "Calming lavender aroma · natural fragrance oil · hangable · 12 pcs pack",
    price: "10.90",
    featured: true,
    cartName: "Scented Sachet — Lavender (12 Pack)",
    tagline: "Floral freshness. Natural elegance.",
    ref: "Y987S023",
    features: [
      { icon: "❧", label: "Natural fragrance oil", text: "Calming lavender scent" },
      { icon: "◷", label: "Long-lasting aroma", text: "Fresh for longer" },
      { icon: "⌂", label: "Any space", text: "Closets, drawers & cars" },
      { icon: "✦", label: "Hangable", text: "Built-in hook" },
    ],
  },

  /* Essential oils */
  {
    id: "lavender-oil",
    name: "Lavender",
    slug: "lavender-oil",
    category: "essential-oils",
    desc: "Calming lavender · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Lavender (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S001",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "coconut-oil",
    name: "Coconut",
    slug: "coconut-oil",
    category: "essential-oils",
    desc: "Creamy coconut · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Coconut (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S002",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "rose-oil",
    name: "Rose",
    slug: "rose-oil",
    category: "essential-oils",
    desc: "Romantic rose · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Rose (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S003",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "vanilla-oil",
    name: "Vanilla",
    slug: "vanilla-oil",
    category: "essential-oils",
    desc: "Creamy vanilla · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Vanilla (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S004",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "cotton-oil",
    name: "Cotton",
    slug: "cotton-oil",
    category: "essential-oils",
    desc: "Clean cotton · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Cotton (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S005",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "jasmine-oil",
    name: "Jasmine",
    slug: "jasmine-oil",
    category: "essential-oils",
    desc: "Elegant jasmine · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Jasmine (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S006",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "mango-oil",
    name: "Mango",
    slug: "mango-oil",
    category: "essential-oils",
    desc: "Juicy mango · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Mango (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S007",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "strawberry-oil",
    name: "Strawberry",
    slug: "strawberry-oil",
    category: "essential-oils",
    desc: "Sweet strawberry · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Strawberry (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S008",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "orange-cinnamon-oil",
    name: "Orange Cinnamon",
    slug: "orange-cinnamon-oil",
    category: "essential-oils",
    desc: "Orange & cinnamon · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Orange Cinnamon (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S009",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "red-berries-oil",
    name: "Red Berries",
    slug: "red-berries-oil",
    category: "essential-oils",
    desc: "Fresh red berries · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Red Berries (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S010",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "orange-blossom-oil",
    name: "Orange Blossom",
    slug: "orange-blossom-oil",
    category: "essential-oils",
    desc: "Floral orange blossom · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Orange Blossom (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S011",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "ocean-oil",
    name: "Ocean",
    slug: "ocean-oil",
    category: "essential-oils",
    desc: "Fresh ocean · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Ocean (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S012",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "salted-caramel-oil",
    name: "Salted Caramel",
    slug: "salted-caramel-oil",
    category: "essential-oils",
    desc: "Warm salted caramel · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Salted Caramel (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S013",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "lemongrass-oil",
    name: "Lemongrass",
    slug: "lemongrass-oil",
    category: "essential-oils",
    desc: "Fresh lemongrass · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Lemongrass (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S014",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "apple-oil",
    name: "Apple",
    slug: "apple-oil",
    category: "essential-oils",
    desc: "Crisp apple · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Apple (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S015",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "gingerbread-oil",
    name: "Gingerbread",
    slug: "gingerbread-oil",
    category: "essential-oils",
    desc: "Warm gingerbread · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Gingerbread (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S016",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "strawberry-cream-oil",
    name: "Strawberry Cream",
    slug: "strawberry-cream-oil",
    category: "essential-oils",
    desc: "Strawberry cream · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Strawberry Cream (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S017",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "cherry-oil",
    name: "Cherry",
    slug: "cherry-oil",
    category: "essential-oils",
    desc: "Sweet cherry · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Cherry (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S018",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "palo-santo-oil",
    name: "Palo Santo",
    slug: "palo-santo-oil",
    category: "essential-oils",
    desc: "Sacred palo santo · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Palo Santo (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S019",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "lemon-oil",
    name: "Lemon",
    slug: "lemon-oil",
    category: "essential-oils",
    desc: "Fresh lemon · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: false,
    cartName: "Essential Oil — Lemon (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S020",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "cinnamon-oil",
    name: "Cinnamon",
    slug: "cinnamon-oil",
    category: "essential-oils",
    desc: "Warm cinnamon · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Cinnamon (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S021",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },
  {
    id: "eucalyptus-oil",
    name: "Eucalyptus",
    slug: "eucalyptus-oil",
    category: "essential-oils",
    desc: "Fresh eucalyptus · natural & pure · for burners & diffusers · 16 pcs",
    price: "12.90",
    featured: true,
    cartName: "Essential Oil — Eucalyptus (16 Pack)",
    tagline: "Natural essence for your home.",
    ref: "Y987S022",
    features: [
      { icon: "❧", label: "Natural & pure", text: "Plant-based aroma" },
      { icon: "⌂", label: "Warm & cozy", text: "Home atmosphere" },
      { icon: "◷", label: "Long-lasting", text: "Enveloping scent" },
      { icon: "✦", label: "Versatile", text: "Burners & diffusers" },
    ],
  },

  /* Smart aroma diffuser refills */
  {
    id: "lavender-refill",
    name: "Lavender",
    slug: "lavender-refill",
    category: "smart-aroma-refills",
    desc: "Calming lavender · 100 ml · for smart aroma diffusers · 12 pcs",
    price: "15.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Lavender (12 Pack)",
    tagline: "Fresh scent for your smart diffuser.",
    features: [
      { icon: "❧", label: "Lavender aroma", text: "Calm & floral" },
      { icon: "◷", label: "100 ml bottle", text: "3.4 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "lavender-refill-300",
    name: "Lavender — 300 ml",
    slug: "lavender-refill-300",
    category: "smart-aroma-refills",
    desc: "Calming lavender · 300 ml · for smart aroma diffusers · 12 pcs",
    price: "29.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Lavender 300 ml (12 Pack)",
    tagline: "Bigger bottle. Same calming lavender.",
    features: [
      { icon: "❧", label: "Lavender aroma", text: "Calm & floral" },
      { icon: "◷", label: "300 ml bottle", text: "10.1 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "cotton-refill",
    name: "Cotton",
    slug: "cotton-refill",
    category: "smart-aroma-refills",
    desc: "Clean cotton · 100 ml · for smart aroma diffusers · 12 pcs",
    price: "15.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Cotton (12 Pack)",
    tagline: "Fresh scent for your smart diffuser.",
    features: [
      { icon: "❧", label: "Cotton aroma", text: "Clean & soft" },
      { icon: "◷", label: "100 ml bottle", text: "3.4 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "cotton-refill-300",
    name: "Cotton — 300 ml",
    slug: "cotton-refill-300",
    category: "smart-aroma-refills",
    desc: "Clean cotton · 300 ml · for smart aroma diffusers · 12 pcs",
    price: "29.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Cotton 300 ml (12 Pack)",
    tagline: "Bigger bottle. Same clean cotton.",
    features: [
      { icon: "❧", label: "Cotton aroma", text: "Clean & soft" },
      { icon: "◷", label: "300 ml bottle", text: "10.1 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "ocean-refill",
    name: "Ocean",
    slug: "ocean-refill",
    category: "smart-aroma-refills",
    desc: "Fresh ocean · 100 ml · for smart aroma diffusers · 12 pcs",
    price: "15.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Ocean (12 Pack)",
    tagline: "Fresh scent for your smart diffuser.",
    features: [
      { icon: "❧", label: "Ocean aroma", text: "Clean & marine" },
      { icon: "◷", label: "100 ml bottle", text: "3.4 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "ocean-refill-300",
    name: "Ocean — 300 ml",
    slug: "ocean-refill-300",
    category: "smart-aroma-refills",
    desc: "Fresh ocean · 300 ml · for smart aroma diffusers · 12 pcs",
    price: "29.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Ocean 300 ml (12 Pack)",
    tagline: "Bigger bottle. Same ocean breeze.",
    features: [
      { icon: "❧", label: "Ocean aroma", text: "Clean & marine" },
      { icon: "◷", label: "300 ml bottle", text: "10.1 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "rose-refill",
    name: "Rose",
    slug: "rose-refill",
    category: "smart-aroma-refills",
    desc: "Romantic rose · 100 ml · for smart aroma diffusers · 12 pcs",
    price: "15.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Rose (12 Pack)",
    tagline: "Fresh scent for your smart diffuser.",
    features: [
      { icon: "❧", label: "Rose aroma", text: "Soft & floral" },
      { icon: "◷", label: "100 ml bottle", text: "3.4 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "rose-refill-300",
    name: "Rose — 300 ml",
    slug: "rose-refill-300",
    category: "smart-aroma-refills",
    desc: "Romantic rose · 300 ml · for smart aroma diffusers · 12 pcs",
    price: "29.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Rose 300 ml (12 Pack)",
    tagline: "Bigger bottle. Same romantic rose.",
    features: [
      { icon: "❧", label: "Rose aroma", text: "Soft & floral" },
      { icon: "◷", label: "300 ml bottle", text: "10.1 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "cherry-refill",
    name: "Cherry",
    slug: "cherry-refill",
    category: "smart-aroma-refills",
    desc: "Sweet cherry · 100 ml · for smart aroma diffusers · 12 pcs",
    price: "15.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Cherry (12 Pack)",
    tagline: "Fresh scent for your smart diffuser.",
    features: [
      { icon: "❧", label: "Cherry aroma", text: "Sweet & fruity" },
      { icon: "◷", label: "100 ml bottle", text: "3.4 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "cherry-refill-300",
    name: "Cherry — 300 ml",
    slug: "cherry-refill-300",
    category: "smart-aroma-refills",
    desc: "Sweet cherry · 300 ml · for smart aroma diffusers · 12 pcs",
    price: "29.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Cherry 300 ml (12 Pack)",
    tagline: "Bigger bottle. Same sweet cherry.",
    features: [
      { icon: "❧", label: "Cherry aroma", text: "Sweet & fruity" },
      { icon: "◷", label: "300 ml bottle", text: "10.1 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "jasmine-refill",
    name: "Jasmine",
    slug: "jasmine-refill",
    category: "smart-aroma-refills",
    desc: "Elegant jasmine · 100 ml · for smart aroma diffusers · 12 pcs",
    price: "15.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Jasmine (12 Pack)",
    tagline: "Fresh scent for your smart diffuser.",
    features: [
      { icon: "❧", label: "Jasmine aroma", text: "Elegant & floral" },
      { icon: "◷", label: "100 ml bottle", text: "3.4 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },
  {
    id: "jasmine-refill-300",
    name: "Jasmine — 300 ml",
    slug: "jasmine-refill-300",
    category: "smart-aroma-refills",
    desc: "Elegant jasmine · 300 ml · for smart aroma diffusers · 12 pcs",
    price: "29.90",
    featured: true,
    cartName: "Smart Aroma Diffuser Refill — Jasmine 300 ml (12 Pack)",
    tagline: "Bigger bottle. Same elegant jasmine.",
    features: [
      { icon: "❧", label: "Jasmine aroma", text: "Elegant & floral" },
      { icon: "◷", label: "300 ml bottle", text: "10.1 fl oz each" },
      { icon: "✦", label: "Smart diffuser", text: "Easy refill tip" },
      { icon: "⌂", label: "12 pcs pack", text: "Ready to display" },
    ],
  },

  /* Smart aroma diffusers (machines) */
  {
    id: "smart-diffuser-aurora",
    name: "Aurora — YS-A100",
    slug: "smart-diffuser-aurora",
    category: "smart-aroma-diffusers",
    desc: "Iridescent rainbow window · digital timer display · ultra-fine cool mist · USB powered",
    price: "39.90",
    featured: true,
    cartName: "Smart Aroma Diffuser — Aurora (Model YS-A100)",
    tagline: "A glow of colour with every breath of scent.",
    images: ["smart-diffuser-aurora", "smart-diffuser-aurora-lifestyle"],
    features: [
      { icon: "✦", label: "Aurora glow", text: "Iridescent light window" },
      { icon: "◷", label: "Smart timer", text: "Digital interval display" },
      { icon: "❧", label: "Ultra-fine mist", text: "Quiet cool mist" },
      { icon: "⌂", label: "USB powered", text: "Works in any room" },
    ],
  },
  {
    id: "smart-diffuser-halo",
    name: "Halo — YS-A200",
    slug: "smart-diffuser-halo",
    category: "smart-aroma-diffusers",
    desc: "Round porthole tank with level dial · digital timer display · steady cool mist · one-touch control",
    price: "39.90",
    featured: true,
    cartName: "Smart Aroma Diffuser — Halo (Model YS-A200)",
    tagline: "Classic dial design, effortless fragrance.",
    images: ["smart-diffuser-halo", "smart-diffuser-halo-lifestyle"],
    features: [
      { icon: "◍", label: "Porthole tank", text: "See the scent level" },
      { icon: "◷", label: "Smart timer", text: "Digital interval display" },
      { icon: "❧", label: "Steady mist", text: "Consistent diffusion" },
      { icon: "⌂", label: "One-touch", text: "Simple single button" },
    ],
  },
  {
    id: "smart-diffuser-kitty",
    name: "Kitty — YS-A300",
    slug: "smart-diffuser-kitty",
    category: "smart-aroma-diffusers",
    desc: "Playful cat-ear design · round view window · gentle cool mist · compact for desks & shelves",
    price: "39.90",
    featured: true,
    cartName: "Smart Aroma Diffuser — Kitty (Model YS-A300)",
    tagline: "The cutest way to scent your space.",
    images: ["smart-diffuser-kitty", "smart-diffuser-kitty-lifestyle"],
    features: [
      { icon: "✦", label: "Cat-ear design", text: "Playful & charming" },
      { icon: "◍", label: "View window", text: "See the scent level" },
      { icon: "❧", label: "Gentle mist", text: "Quiet cool mist" },
      { icon: "⌂", label: "Compact size", text: "Desks & shelves" },
    ],
  },
];

window.YINSCENT_CATEGORIES = [
  {
    id: "tealights",
    label: "Scented tealight candles",
    anchor: "#tealights",
    gridId: "productGrid",
  },
  {
    id: "scented-candles",
    label: "Scented candles",
    anchor: "#scented-candles",
    gridId: "candleGrid",
  },
  {
    id: "reed-diffusers",
    label: "Reed diffusers",
    anchor: "#reed-diffusers",
    gridId: "diffuserGrid",
  },
  {
    id: "tealight-holders",
    label: "Tealight holders",
    anchor: "#tealight-holders",
    gridId: "holderGrid",
  },
  {
    id: "scented-sachets",
    label: "Scented sachets",
    anchor: "#scented-sachets",
    gridId: "sachetGrid",
  },
  {
    id: "essential-oils",
    label: "Essential oils",
    anchor: "#essential-oils",
    gridId: "oilGrid",
  },
  {
    id: "smart-aroma-refills",
    label: "Smart aroma diffuser refill",
    anchor: "#smart-aroma-refills",
    gridId: "refillGrid",
  },
  {
    id: "smart-aroma-diffusers",
    label: "Smart aroma diffuser",
    anchor: "#smart-aroma-diffusers",
    gridId: "smartDiffuserGrid",
  },
];

window.YINSCENT_CATEGORY = "Scented tealight candles";
