window.YINSCENT_PRODUCTS = [
  { id: "apple", name: "Apple", slug: "apple", desc: "Juicy apple aroma", price: "5.99", featured: true },
  { id: "cotton", name: "Cotton", slug: "cotton", desc: "Soft cotton aroma", price: "5.99", featured: false },
  { id: "orange-blossom", name: "Orange Blossom", slug: "orange-blossom", desc: "Refreshing orange blossom aroma", price: "5.99", featured: false },
  { id: "cherry", name: "Cherry", slug: "cherry", desc: "Sweet cherry aroma", price: "5.99", featured: false },
  { id: "coconut", name: "Coconut", slug: "coconut", desc: "Fresh coconut aroma", price: "5.99", featured: false },
  { id: "cinnamon", name: "Cinnamon", slug: "cinnamon", desc: "Warm cinnamon aroma", price: "5.99", featured: true },
  { id: "rose", name: "Rose", slug: "rose", desc: "Romantic rose aroma", price: "5.99", featured: true },
  { id: "lavender", name: "Lavender", slug: "lavender", desc: "Relaxing lavender aroma", price: "5.99", featured: true },
  { id: "jasmine", name: "Jasmine", slug: "jasmine", desc: "Delicate jasmine aroma", price: "5.99", featured: false },
  { id: "vanilla", name: "Vanilla", slug: "vanilla", desc: "Creamy vanilla aroma", price: "5.99", featured: true },
  { id: "strawberry-cream", name: "Strawberry Cream", slug: "strawberry-cream", desc: "Sweet strawberry cream aroma", price: "5.99", featured: false },
  { id: "mango", name: "Mango", slug: "mango", desc: "Juicy mango aroma", price: "5.99", featured: false },
  { id: "ocean", name: "Ocean", slug: "ocean", desc: "Fresh ocean aroma", price: "5.99", featured: true },

  /* 9-pack scented tea light candles (new line) */
  { id: "lavender-pack", name: "Lavender — 9 Pack", slug: "lavender-pack", desc: "Calming lavender · 9 tea lights · smokeless clean burn", price: "8.99", featured: true, cartName: "Scented Tea Light Candles — Lavender (9 Pack)" },
  { id: "cotton-pack", name: "Cotton — 9 Pack", slug: "cotton-pack", desc: "Clean cotton · 9 tea lights · smokeless clean burn", price: "8.99", featured: false, cartName: "Scented Tea Light Candles — Cotton (9 Pack)" },
  { id: "cherry-pack", name: "Cherry — 9 Pack", slug: "cherry-pack", desc: "Sweet cherry · 9 tea lights · smokeless clean burn", price: "8.99", featured: true, cartName: "Scented Tea Light Candles — Cherry (9 Pack)" },
  { id: "apple-pack", name: "Apple — 9 Pack", slug: "apple-pack", desc: "Crisp apple · 9 tea lights · smokeless clean burn", price: "8.99", featured: true, cartName: "Scented Tea Light Candles — Apple (9 Pack)" },
  { id: "rose-pack", name: "Rose — 9 Pack", slug: "rose-pack", desc: "Romantic rose · 9 tea lights · smokeless clean burn", price: "8.99", featured: false, cartName: "Scented Tea Light Candles — Rose (9 Pack)" },
  { id: "jasmine-pack", name: "Jasmine — 9 Pack", slug: "jasmine-pack", desc: "Delicate jasmine · 9 tea lights · smokeless clean burn", price: "8.99", featured: false, cartName: "Scented Tea Light Candles — Jasmine (9 Pack)" },
  { id: "coconut-pack", name: "Coconut — 9 Pack", slug: "coconut-pack", desc: "Creamy coconut · 9 tea lights · smokeless clean burn", price: "8.99", featured: false, cartName: "Scented Tea Light Candles — Coconut (9 Pack)" },
  { id: "cinnamon-pack", name: "Cinnamon — 9 Pack", slug: "cinnamon-pack", desc: "Warm cinnamon · 9 tea lights · smokeless clean burn", price: "8.99", featured: true, cartName: "Scented Tea Light Candles — Cinnamon (9 Pack)" },
  { id: "mango-pack", name: "Mango — 9 Pack", slug: "mango-pack", desc: "Sweet mango · 9 tea lights · smokeless clean burn", price: "8.99", featured: false, cartName: "Scented Tea Light Candles — Mango (9 Pack)" },
  { id: "vanilla-pack", name: "Vanilla — 9 Pack", slug: "vanilla-pack", desc: "Rich vanilla · 9 tea lights · smokeless clean burn", price: "8.99", featured: false, cartName: "Scented Tea Light Candles — Vanilla (9 Pack)" },
  { id: "ocean-pack", name: "Ocean — 9 Pack", slug: "ocean-pack", desc: "Fresh ocean breeze · 9 tea lights · smokeless clean burn", price: "8.99", featured: true, cartName: "Scented Tea Light Candles — Ocean (9 Pack)" },

  /* Cozy collection — scented tealight candles (additional line, new images) */
  { id: "vanilla-cozy", name: "Vanilla — Cozy", slug: "vanilla-cozy", desc: "Creamy vanilla aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Vanilla (Cozy)" },
  { id: "cotton-cozy", name: "Cotton — Cozy", slug: "cotton-cozy", desc: "Soft cotton aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Cotton (Cozy)" },
  { id: "cherry-cozy", name: "Cherry — Cozy", slug: "cherry-cozy", desc: "Sweet cherry aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Cherry (Cozy)" },
  { id: "cinnamon-cozy", name: "Cinnamon — Cozy", slug: "cinnamon-cozy", desc: "Warm cinnamon aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Cinnamon (Cozy)" },
  { id: "rose-cozy", name: "Rose — Cozy", slug: "rose-cozy", desc: "Romantic rose aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Rose (Cozy)" },
  { id: "mango-cozy", name: "Mango — Cozy", slug: "mango-cozy", desc: "Juicy mango aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Mango (Cozy)" },
  { id: "lavender-cozy", name: "Lavender — Cozy", slug: "lavender-cozy", desc: "Relaxing lavender aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Lavender (Cozy)" },
  { id: "ocean-cozy", name: "Ocean — Cozy", slug: "ocean-cozy", desc: "Fresh ocean aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Ocean (Cozy)" },
  { id: "jasmine-cozy", name: "Jasmine — Cozy", slug: "jasmine-cozy", desc: "Delicate jasmine aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Jasmine (Cozy)" },
  { id: "apple-cozy", name: "Apple — Cozy", slug: "apple-cozy", desc: "Juicy apple aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Apple (Cozy)" },
  { id: "coconut-cozy", name: "Coconut — Cozy", slug: "coconut-cozy", desc: "Fresh coconut aroma · long lasting burn · premium wax", price: "5.99", featured: false, cartName: "Scented Tealight Candles — Coconut (Cozy)" },

  /* Scented candles — jar collection */
  {
    id: "cotton-candle",
    name: "Cotton",
    slug: "cotton-candle",
    category: "scented-candles",
    desc: "Fresh cotton · clean & soft · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Cotton (260g)",
    tagline: "Fresh. Soft. Comforting.",
    images: ["cotton-candle", "cotton-candle-lit", "cotton-candle-display"],
    features: [
      { icon: "☁", label: "Fresh cotton", text: "Clean & soft" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "orange-blossom-candle",
    name: "Orange Blossom",
    slug: "orange-blossom-candle",
    category: "scented-candles",
    desc: "Bright orange blossom · floral & refreshing · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Orange Blossom (260g)",
    tagline: "Bright. Floral. Refreshing.",
    images: ["orange-blossom-candle", "orange-blossom-candle-lit", "orange-blossom-candle-display"],
    features: [
      { icon: "✿", label: "Orange blossom", text: "Floral & refreshing" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "apple-candle",
    name: "Apple",
    slug: "apple-candle",
    category: "scented-candles",
    desc: "Crisp apple · fresh & delightful · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Apple (260g)",
    tagline: "Crisp. Fresh. Delightful.",
    images: ["apple-candle", "apple-candle-lit", "apple-candle-display"],
    features: [
      { icon: "◆", label: "Crisp apple", text: "Fresh & delightful" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "lavender-candle",
    name: "Lavender",
    slug: "lavender-candle",
    category: "scented-candles",
    desc: "Soothing lavender · calm & relax · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Lavender (260g)",
    tagline: "Relax. Unwind. Breathe.",
    images: ["lavender-candle", "lavender-candle-lit", "lavender-candle-display"],
    features: [
      { icon: "❀", label: "Soothing lavender", text: "Calm & relax" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "rose-candle",
    name: "Rose",
    slug: "rose-candle",
    category: "scented-candles",
    desc: "Romantic rose · soft & floral · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Rose (260g)",
    tagline: "Romantic. Elegant. Timeless.",
    images: ["rose-candle-lit", "rose-candle", "rose-candle-display"],
    features: [
      { icon: "✿", label: "Romantic rose", text: "Soft & floral" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "ocean-candle",
    name: "Ocean",
    slug: "ocean-candle",
    category: "scented-candles",
    desc: "Fresh ocean · clean & refreshing · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Ocean (260g)",
    tagline: "Fresh. Clean. Refreshing.",
    images: ["ocean-candle", "ocean-candle-lit", "ocean-candle-display"],
    features: [
      { icon: "≋", label: "Fresh ocean", text: "Clean & refreshing" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "mango-candle",
    name: "Mango",
    slug: "mango-candle",
    category: "scented-candles",
    desc: "Juicy mango · sweet & tropical · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Mango (260g)",
    tagline: "Tropical. Sweet. Uplifting.",
    images: ["mango-candle-lit", "mango-candle", "mango-candle-display"],
    features: [
      { icon: "◆", label: "Juicy mango", text: "Sweet & tropical" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "jasmine-candle",
    name: "Jasmine",
    slug: "jasmine-candle",
    category: "scented-candles",
    desc: "Jasmine blossom · elegant & floral · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Jasmine (260g)",
    tagline: "Elegant. Floral. Soothing.",
    images: ["jasmine-candle", "jasmine-candle-lit", "jasmine-candle-display"],
    features: [
      { icon: "❀", label: "Jasmine blossom", text: "Elegant & floral" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },
  {
    id: "cinnamon-candle",
    name: "Cinnamon",
    slug: "cinnamon-candle",
    category: "scented-candles",
    desc: "Warm cinnamon · spicy & comforting · up to 45 hours · 260g",
    price: "12.99",
    featured: true,
    cartName: "Scented Candle — Cinnamon (260g)",
    tagline: "Warm. Spicy. Comforting.",
    images: ["cinnamon-candle", "cinnamon-candle-lit", "cinnamon-candle-display"],
    features: [
      { icon: "✦", label: "Warm cinnamon", text: "Spicy & comforting" },
      { icon: "◷", label: "Long lasting", text: "Up to 45 hours" },
      { icon: "❧", label: "Relaxing", text: "Calm your mind" },
      { icon: "⌂", label: "Any space", text: "Perfect for home" },
    ],
  },

  /* Reed diffusers */
  {
    id: "apple-diffuser",
    name: "Apple",
    slug: "apple-diffuser",
    category: "reed-diffusers",
    desc: "Sweet & juicy apple · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Apple",
    tagline: "Sweet. Juicy. Comforting.",
    features: [
      { icon: "◆", label: "Sweet apple", text: "Juicy & comforting" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & comforting" },
    ],
  },
  {
    id: "mango-diffuser",
    name: "Mango",
    slug: "mango-diffuser",
    category: "reed-diffusers",
    desc: "Vivid & juicy mango · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Mango",
    tagline: "Sweet. Tropical. Refreshing.",
    features: [
      { icon: "◆", label: "Juicy mango", text: "Vivid & tropical" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & uplifting" },
    ],
  },
  {
    id: "cinnamon-diffuser",
    name: "Cinnamon",
    slug: "cinnamon-diffuser",
    category: "reed-diffusers",
    desc: "Warm & spicy cinnamon · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Cinnamon",
    tagline: "Warm. Spicy. Comforting.",
    features: [
      { icon: "✦", label: "Warm cinnamon", text: "Spicy & cozy" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & comforting" },
    ],
  },
  {
    id: "cotton-diffuser",
    name: "Cotton",
    slug: "cotton-diffuser",
    category: "reed-diffusers",
    desc: "Pure & clean cotton · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Cotton",
    tagline: "Fresh. Clean. Comforting.",
    features: [
      { icon: "☁", label: "Pure cotton", text: "Clean & soft" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & relaxing" },
    ],
  },
  {
    id: "cherry-diffuser",
    name: "Cherry",
    slug: "cherry-diffuser",
    category: "reed-diffusers",
    desc: "Sweet & delicate cherry · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Cherry",
    tagline: "Sweet. Fruity. Delicate.",
    features: [
      { icon: "◆", label: "Sweet cherry", text: "Fruity & delicate" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & relaxing" },
    ],
  },
  {
    id: "ocean-diffuser",
    name: "Ocean",
    slug: "ocean-diffuser",
    category: "reed-diffusers",
    desc: "Fresh & marine ocean · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Ocean",
    tagline: "Fresh. Clean. Refreshing.",
    features: [
      { icon: "≋", label: "Fresh ocean", text: "Marine & clean" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & relaxing" },
    ],
  },
  {
    id: "jasmine-diffuser",
    name: "Jasmine",
    slug: "jasmine-diffuser",
    category: "reed-diffusers",
    desc: "Elegant & floral jasmine · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Jasmine",
    tagline: "Pure. Floral. Serene.",
    features: [
      { icon: "❀", label: "Jasmine blossom", text: "Elegant & floral" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & relaxing" },
    ],
  },
  {
    id: "lavender-diffuser",
    name: "Lavender",
    slug: "lavender-diffuser",
    category: "reed-diffusers",
    desc: "Relaxing lavender · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Lavender",
    tagline: "Breathe in lavender. Feel the calm.",
    features: [
      { icon: "❀", label: "Soothing lavender", text: "Calm & relax" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & comforting" },
    ],
  },
  {
    id: "orange-blossom-diffuser",
    name: "Orange Blossom",
    slug: "orange-blossom-diffuser",
    category: "reed-diffusers",
    desc: "Fresh & floral orange blossom · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Orange Blossom",
    tagline: "Fresh. Floral. Uplifting.",
    features: [
      { icon: "✿", label: "Orange blossom", text: "Floral & refreshing" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & relaxing" },
    ],
  },
  {
    id: "coconut-diffuser",
    name: "Coconut",
    slug: "coconut-diffuser",
    category: "reed-diffusers",
    desc: "Tropical & creamy coconut · natural rattan sticks · up to 8+ weeks",
    price: "14.99",
    featured: true,
    cartName: "Reed Diffuser — Coconut",
    tagline: "Tropical. Creamy. Comforting.",
    features: [
      { icon: "◆", label: "Creamy coconut", text: "Tropical & soothing" },
      { icon: "❧", label: "Rattan sticks", text: "Natural diffusion" },
      { icon: "◷", label: "Long lasting", text: "Up to 8+ weeks" },
      { icon: "⌂", label: "Any space", text: "Calm & relaxing" },
    ],
  },

  /* Tealight holders */
  {
    id: "square-tealight-holder",
    name: "Square — 12 Pack",
    slug: "square-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · square shape · 7.5 × 4.3 cm · 12 pcs value pack",
    price: "11.99",
    featured: true,
    cartName: "Tealight Holder — Square (12 Pack)",
    tagline: "Elegant. Transparent. Timeless.",
    features: [
      { icon: "▢", label: "Square shape", text: "Modern & clean" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
  {
    id: "star-tealight-holder",
    name: "Star — 12 Pack",
    slug: "star-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · star shape · 9.8 × 4.3 cm · 12 pcs value pack",
    price: "11.99",
    featured: true,
    cartName: "Tealight Holder — Star (12 Pack)",
    tagline: "Sparkling. Charming. Festive.",
    features: [
      { icon: "★", label: "Star shape", text: "Eye-catching glow" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
  {
    id: "heart-tealight-holder",
    name: "Heart — 12 Pack",
    slug: "heart-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · heart shape · 8.5 × 4.2 cm · 12 pcs value pack",
    price: "11.99",
    featured: true,
    cartName: "Tealight Holder — Heart (12 Pack)",
    tagline: "Romantic. Warm. Delightful.",
    features: [
      { icon: "♥", label: "Heart shape", text: "Romantic & warm" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
  {
    id: "plum-blossom-tealight-holder",
    name: "Plum Blossom — 12 Pack",
    slug: "plum-blossom-tealight-holder",
    category: "tealight-holders",
    desc: "Crystal clear glass · plum blossom shape · 9.5 × 4.3 cm · 12 pcs value pack",
    price: "11.99",
    featured: true,
    cartName: "Tealight Holder — Plum Blossom (12 Pack)",
    tagline: "Floral. Graceful. Radiant.",
    features: [
      { icon: "✿", label: "Plum blossom", text: "Floral & graceful" },
      { icon: "◇", label: "Crystal clear glass", text: "Maximum light" },
      { icon: "⛨", label: "Sturdy & durable", text: "Built to last" },
      { icon: "✦", label: "Any occasion", text: "Home, parties & weddings" },
    ],
  },
];

window.YINSCENT_CATEGORIES = [
  {
    id: "tealights",
    label: "Scented tealight candles",
    anchor: "#tealights",
    gridId: "productGrid",
  },
  {
    id: "scented-candles",
    label: "Scented candles",
    anchor: "#scented-candles",
    gridId: "candleGrid",
  },
  {
    id: "reed-diffusers",
    label: "Reed diffusers",
    anchor: "#reed-diffusers",
    gridId: "diffuserGrid",
  },
  {
    id: "tealight-holders",
    label: "Tealight holders",
    anchor: "#tealight-holders",
    gridId: "holderGrid",
  },
];

window.YINSCENT_CATEGORY = "Scented tealight candles";
